services:
  kernel-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wsl-kernel-compiler
    volumes:
      - ./out:/out
      - wsl-kernel-source:/workspace
    stdin_open: true
    tty: true
    environment:
      - TZ=America/Sao_Paulo

volumes:
  wsl-kernel-source:
    name: wsl-kernel-source
